project_name: kwwhat-chat-BI
databases:
  - name: snowflake
    type: snowflake
    credentials_path: databases/snowflake.json
    include:
      - DBT_PROD.fact_*
      - DBT_PROD.dim_*
    accessors:
      - columns
      - description
      - preview
repos: []
